# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jiaxin/yh3dr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jiaxin/yh3dr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiaxin/yh3dr/CMakeFiles /home/jiaxin/yh3dr//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiaxin/yh3dr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xsfm_exe

# Build rule for target.
xsfm_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xsfm_exe
.PHONY : xsfm_exe

# fast build rule for target.
xsfm_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/build
.PHONY : xsfm_exe/fast

#=============================================================================
# Target rules for targets named mvg

# Build rule for target.
mvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mvg
.PHONY : mvg

# fast build rule for target.
mvg/fast:
	$(MAKE) $(MAKESILENT) -f libmvg/CMakeFiles/mvg.dir/build.make libmvg/CMakeFiles/mvg.dir/build
.PHONY : mvg/fast

#=============================================================================
# Target rules for targets named lsd

# Build rule for target.
lsd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsd
.PHONY : lsd

# fast build rule for target.
lsd/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/LSD/CMakeFiles/lsd.dir/build.make thirdParty/LSD/CMakeFiles/lsd.dir/build
.PHONY : lsd/fast

#=============================================================================
# Target rules for targets named pba

# Build rule for target.
pba: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pba
.PHONY : pba

# fast build rule for target.
pba/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/PBA/CMakeFiles/pba.dir/build.make thirdParty/PBA/CMakeFiles/pba.dir/build
.PHONY : pba/fast

#=============================================================================
# Target rules for targets named poisson_recon

# Build rule for target.
poisson_recon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poisson_recon
.PHONY : poisson_recon

# fast build rule for target.
poisson_recon/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/PoissonRecon/CMakeFiles/poisson_recon.dir/build.make thirdParty/PoissonRecon/CMakeFiles/poisson_recon.dir/build
.PHONY : poisson_recon/fast

#=============================================================================
# Target rules for targets named vlfeat

# Build rule for target.
vlfeat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vlfeat
.PHONY : vlfeat

# fast build rule for target.
vlfeat/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/VLFeat/CMakeFiles/vlfeat.dir/build.make thirdParty/VLFeat/CMakeFiles/vlfeat.dir/build
.PHONY : vlfeat/fast

#=============================================================================
# Target rules for targets named TinyEXIF

# Build rule for target.
TinyEXIF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TinyEXIF
.PHONY : TinyEXIF

# fast build rule for target.
TinyEXIF/fast:
	$(MAKE) $(MAKESILENT) -f thirdParty/TinyEXIF-master/CMakeFiles/TinyEXIF.dir/build.make thirdParty/TinyEXIF-master/CMakeFiles/TinyEXIF.dir/build
.PHONY : TinyEXIF/fast

sfm/feature/UCamera.o: sfm/feature/UCamera.cpp.o
.PHONY : sfm/feature/UCamera.o

# target to build an object file
sfm/feature/UCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UCamera.cpp.o
.PHONY : sfm/feature/UCamera.cpp.o

sfm/feature/UCamera.i: sfm/feature/UCamera.cpp.i
.PHONY : sfm/feature/UCamera.i

# target to preprocess a source file
sfm/feature/UCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UCamera.cpp.i
.PHONY : sfm/feature/UCamera.cpp.i

sfm/feature/UCamera.s: sfm/feature/UCamera.cpp.s
.PHONY : sfm/feature/UCamera.s

# target to generate assembly for a file
sfm/feature/UCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UCamera.cpp.s
.PHONY : sfm/feature/UCamera.cpp.s

sfm/feature/UImage.o: sfm/feature/UImage.cpp.o
.PHONY : sfm/feature/UImage.o

# target to build an object file
sfm/feature/UImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UImage.cpp.o
.PHONY : sfm/feature/UImage.cpp.o

sfm/feature/UImage.i: sfm/feature/UImage.cpp.i
.PHONY : sfm/feature/UImage.i

# target to preprocess a source file
sfm/feature/UImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UImage.cpp.i
.PHONY : sfm/feature/UImage.cpp.i

sfm/feature/UImage.s: sfm/feature/UImage.cpp.s
.PHONY : sfm/feature/UImage.s

# target to generate assembly for a file
sfm/feature/UImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UImage.cpp.s
.PHONY : sfm/feature/UImage.cpp.s

sfm/feature/UMatching.o: sfm/feature/UMatching.cpp.o
.PHONY : sfm/feature/UMatching.o

# target to build an object file
sfm/feature/UMatching.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UMatching.cpp.o
.PHONY : sfm/feature/UMatching.cpp.o

sfm/feature/UMatching.i: sfm/feature/UMatching.cpp.i
.PHONY : sfm/feature/UMatching.i

# target to preprocess a source file
sfm/feature/UMatching.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UMatching.cpp.i
.PHONY : sfm/feature/UMatching.cpp.i

sfm/feature/UMatching.s: sfm/feature/UMatching.cpp.s
.PHONY : sfm/feature/UMatching.s

# target to generate assembly for a file
sfm/feature/UMatching.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/sfm/feature/UMatching.cpp.s
.PHONY : sfm/feature/UMatching.cpp.s

xsfm.o: xsfm.cpp.o
.PHONY : xsfm.o

# target to build an object file
xsfm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/xsfm.cpp.o
.PHONY : xsfm.cpp.o

xsfm.i: xsfm.cpp.i
.PHONY : xsfm.i

# target to preprocess a source file
xsfm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/xsfm.cpp.i
.PHONY : xsfm.cpp.i

xsfm.s: xsfm.cpp.s
.PHONY : xsfm.s

# target to generate assembly for a file
xsfm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xsfm_exe.dir/build.make CMakeFiles/xsfm_exe.dir/xsfm.cpp.s
.PHONY : xsfm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... TinyEXIF"
	@echo "... lsd"
	@echo "... mvg"
	@echo "... pba"
	@echo "... poisson_recon"
	@echo "... vlfeat"
	@echo "... xsfm_exe"
	@echo "... sfm/feature/UCamera.o"
	@echo "... sfm/feature/UCamera.i"
	@echo "... sfm/feature/UCamera.s"
	@echo "... sfm/feature/UImage.o"
	@echo "... sfm/feature/UImage.i"
	@echo "... sfm/feature/UImage.s"
	@echo "... sfm/feature/UMatching.o"
	@echo "... sfm/feature/UMatching.i"
	@echo "... sfm/feature/UMatching.s"
	@echo "... xsfm.o"
	@echo "... xsfm.i"
	@echo "... xsfm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

